### ISSUE TITLE
sddm-sugar-candy-git install had failed

### ISSUE THREAD

**Issue by sambuaneesh** [SolDoesTech/HyprV4#11]
No matter in how many different ways i run the script, same is happening
[ERROR] - sddm-sugar-candy-git install had failed, please check the install.log

heres the log

:: ^[[1m(1/1) Parsing SRCINFO: sddm-sugar-candy-git^[[0m
==> Making package: sddm-sugar-candy-git r53.2b72ef6-1 (Sunday 21 May 2023 11:4>
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning sugar-candy git repo...
Cloning into bare repository '/home/stealthspectre/.cache/yay/sddm-sugar-candy->
fatal: unable to access 'https://framagit.org/MarianArlt/sddm-sugar-candy.git/'>
==> ERROR: Failure while downloading sugar-candy git repo
    Aborting...
 -> error making: sddm-sugar-candy-git-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
sddm-sugar-candy-git - exit status 1

**Comment by BetaQuasi** [comment]
The failure is there in the error message - for some reason you cannot connect/clone the sugar candy git repo.  What happens if you try to do it manually on another machine?

`git clone https://framagit.org/MarianArlt/sddm-sugar-candy.git`

**Comment by lightspeed-skhattane** [comment]
33% of `curl -I https://framagit.org/MarianArlt/sddm-sugar-candy.git` return a 500
I sent an email to Framasoft... Will see

**Comment by Clutchnp** [comment]
@BetaQuasi  i am having the same error as the OP and this is the error after manually cloning `fatal: unable to access 'https://framagit.org/MarianArlt/sddm-sugar-candy.git/': Failed to connect to framagit.org port 443 after 131958 ms: Couldn't connect to server`

**Comment by BetaQuasi** [comment]
Looks like Lightspeed covered this in his post - seems I just got lucky and managed to clone it in between whatever quota system they have interrupting things :)  Probably due to my timezone (Australia.)

**Comment by Clutchnp** [comment]
Maybe using a VPN will help 🤔. I will try setting it up after reaching home after work .

**Comment by SolDoesTech** [comment]
I remove the sugar-candy package from the script and added the Dependencies needed for the theme to work with out this package. Tested the install multiple times and it looks good. Please get a fresh copy of the set-hypr script, it should fix the issue.
