### ISSUE TITLE
no other workspaces 

### ISSUE THREAD

**Issue by karomba** [SolDoesTech/HyprV4#3]
so in my hyprland i only have 1 workspace and if a try to create another one it does nothing,it's been happening with every wm and it's never happened before.

**Comment by JesseKoldewijn** [comment]
> so in my hyprland i only have 1 workspace and if a try to create another one it does nothing,it's been happening with every wm and it's never happened before.

Did you try switching workspaces with META+2 (or 3, 4, 5 etc) where META is the windows key or command (I believe) if using a macos keyboard.

**Comment by karomba** [comment]
> > so in my hyprland i only have 1 workspace and if a try to create another one it does nothing,it's been happening with every wm and it's never happened before.
> 
> Did you try switching workspaces with META+2 (or 3, 4, 5 etc) where META is the windows key or command (I believe) if using a macos keyboard.

yes i have tried that but it doesn't work

**Comment by JesseKoldewijn** [comment]
weird, maybe remove the HyprV and hypr directory in your ~/.config directory uninstall hyprland-nvidia go into a tty and re-run the set-hypr script

**Comment by karomba** [comment]
this is how it looks
https://github.com/SolDoesTech/HyprV4/assets/115472913/7749bc19-31cf-4dbc-a741-39a2468eebe2

**Comment by JesseKoldewijn** [comment]
And nothing happends when you click on windows-key + 2 or something?
If so, it kinda more sounds like you have a mismatched keyboard layout

**Comment by karomba** [comment]
it works with a us keyboard

**Comment by JesseKoldewijn** [comment]
the default setup is configured to use the us keyboard layout (qwerty) so I think it my not understand the windows/meta key with your current config. You can change the keyboard layout in the hypr config.

**Comment by karomba** [comment]
![swappy-20230518_142602](https://github.com/SolDoesTech/HyprV4/assets/115472913/0657062f-47bf-48ba-9f65-9f0240f3a75c)
this is my current config for the keyboard

**Comment by JesseKoldewijn** [comment]
> > hyprctl keyword input:kb_layout fr
> 
> it says ok

I expect if you do `hyprctl keyword input:kb_variant azerty` it wont say ok

**Comment by karomba** [comment]
> hyprctl keyword input:kb_variant azerty

it does say ok

**Comment by JesseKoldewijn** [comment]
aight, tbh I've never really used a azerty layout on any system so forgive these possibly useless troubleshooting steps. 

have you tried the config if you quote out the kb_variant and kb_model line? 

ps. in between these types of changes in the config it could be possible you'll need to reload hyprland manually. this can most practically be done through a system reboot but sometimes a logout does the trick. I noticed some config settings can be sort of sticky with regards to instant config refresh.

**Comment by karomba** [comment]
like this 
![image](https://github.com/SolDoesTech/HyprV4/assets/115472913/9f81ed9f-a184-45d2-9717-b68abbc57a73)

**Comment by JesseKoldewijn** [comment]
> like this 
> ![image](https://github.com/SolDoesTech/HyprV4/assets/115472913/9f81ed9f-a184-45d2-9717-b68abbc57a73)
> 

Yes

**Comment by aleksandar-code** [comment]
> so in my hyprland i only have 1 workspace and if a try to create another one it does nothing,it's been happening with every wm and it's never happened before.

Hello @karomba  , i had the same problem as an azerty user. The solution is to use keycodes for binding workspaces. 

To find out what your keycodes are for keys, install the package wev, and then you'll be able to see any event happening in a window  created by wev script.

then put the desired keycodes in your ~/.config/hypr/hyprland.conf

Here is my config but your keycodes might differ as french keyboards aren't all equal.

I hope this solves your issue and it can get closed! :smile: 

![image](https://github.com/SolDoesTech/HyprV4/assets/83082486/a49268c6-95b1-4202-85f9-d891cf1ea41d)

**Comment by karomba** [comment]
> > so in my hyprland i only have 1 workspace and if a try to create another one it does nothing,it's been happening with every wm and it's never happened before.
> 
> Hello @karomba , i had the same problem as an azerty user. The solution is to use keycodes for binding workspaces.
> 
> To find out what your keycodes are for keys, install the package wev, and then you'll be able to see any event happening in a window created by wev script.
> 
> then put the desired keycodes in your ~/.config/hypr/hyprland.conf
> 
> Here is my config but your keycodes might differ as french keyboards aren't all equal.
> 
> I hope this solves your issue and it can get closed! smile
> 
> ![image](https://user-images.githubusercontent.com/83082486/248259540-a49268c6-95b1-4202-85f9-d891cf1ea41d.png)

i knew the solution but i forgot to close this issue,by the way for my solution i just found some keybinding for the number row in the sway github.

**Comment by karomba** [comment]
goodbye
