### ISSUE TITLE
No sound on the laptop speaker

### ISSUE THREAD

**Issue by nizarfadlan** [SolDoesTech/HyprV4#33]
I don't know where the problem is, the sound is not there if I don't use bluetooth earphones. If you use laptop speakers then the sound does not come out

**Comment by ttindall23** [comment]
All you need to do is restart pulseaudio.. -- Command Below.

systemctl --user restart pulseaudio

After that, once you click on the audio button it should say audio ON.

**Comment by nizarfadlan** [comment]
> All you need to do is restart pulseaudio.. -- Command Below.
> 
> systemctl --user restart pulseaudio
> 
> After that, once you click on the audio button it should say audio ON.

Is it the same if using pipewire?

**Comment by ttindall23** [comment]
try this:

systemctl --user restart pipewire.service

or

systemctl --user restart pipewire-pulse.service

Also, if neither of those work you can try these below!
______________________________________________________________________________________________________________________________________

systemctl --user restart pipewire.socket

then

systemctl --user --now enable pipewire

**Comment by Paulie420** [comment]
My sound isn't working, either - and I don't have pulseaudio. I do have pipewire and libpipewire; but don't see pipewire.socket or pipewire-pulse.service... hmmmm. I used the HyprV4 script, but have modified it a bit... still, tho, no sound since first install. 
I'm sure I'll hit it - but watching this for any help. :P

**Comment by nizarfadlan** [comment]
> try this:
> 
> systemctl --user restart pipewire.service
> 
> or
> 
> systemctl --user restart pipewire-pulse.service
> 
> Also, if neither of those work you can try these below!
> 
> systemctl --user restart pipewire.socket
> 
> then
> 
> systemctl --user --now enable pipewire

Not work for me
