### ISSUE TITLE
Sddm-Sugar-candy-git

### ISSUE THREAD

**Issue by Kelbresqe** [SolDoesTech/HyprV4#4]
Cannot insatall sugar candy
Failed to connect to framagit.org port 443 after 130635 ms: Couldn't connect to server

**Comment by JesseKoldewijn** [comment]
You need to refresh your mirrorlist in that case.

You can try if refreshing of the same mirrors can work like so `sudo pacman -Sy`.

If that doesn't work you'll need to create a new mirrorlist and then redo the previous step right after that.

By following the "automation" segment you prevent your system from running into this issue again: https://wiki.archlinux.org/title/reflector

**Comment by Anshu-Bijarnia** [comment]
> You need to refresh your mirrorlist in that case.
> 
> You can try if refreshing of the same mirrors can work like so `sudo pacman -Sy`.
> 
> If that doesn't work you'll need to create a new mirrorlist and then redo the previous step right after that.
> 
> By following the "automation" segment you prevent your system from running into this issue again: https://wiki.archlinux.org/title/reflector

I dont think this fixes the issue. Any other suggestions?

**Comment by JesseKoldewijn** [comment]
> 

Trust me, it does. this error message means that it can't find that mirror server.

**Comment by Anshu-Bijarnia** [comment]
the git repo is not accessible i guess. even doing yay -S sddm-sugar-candy-git, it gets stuck at the cloning part.

**Comment by schrodingersca8** [comment]
Hi, did anyone solve this issue?
I am having the same issue

**Comment by Kelbresqe** [comment]
I solve my problem. I dont know why but My iss block my connection to framagit.org server. Then i used vpn and problem solved. Thank you everyone

**Comment by schrodingersca8** [comment]
I also have the same issue, my ISP has blocked framagit.org
Can you tell me how to connect to a vpn.

**Comment by Kelbresqe** [comment]
My modem router has own vpn panel. I connect to router with another computer and set openvpn.

**Comment by schrodingersca8** [comment]
> My modem router has own vpn panel. I connect to router with another computer and set openvpn.

Well, I can't do that.
I tried connecting to my mobile hotspot and connect vpn on my mobile 
Still can't ping to framagit.org

**Comment by JesseKoldewijn** [comment]
Install proxychains then😉 
https://archlinux.org/packages/community/x86_64/proxychains-ng/

**Comment by schrodingersca8** [comment]
> Install proxychains then😉 https://archlinux.org/packages/community/x86_64/proxychains-ng/
> 
> @schrodingersca8
Thanks, i will try this.
I know for sure that my ISP is blocking the access to framagit.org.
Can it also be because while installing arch using archinstall, i used my country 'India' for  the mirror?

**Comment by schrodingersca8** [comment]
> 

I did install proxychains.
I didn't change any config
And ran proxychain ./set-hypr
Still could not solve it.
Anything else I can do? Install this package using Pacman or something.
Or do i configure my proxychains config?

**Comment by JesseKoldewijn** [comment]
> > Install proxychains then😉 https://archlinux.org/packages/community/x86_64/proxychains-ng/
> > 
> > @schrodingersca8
> Thanks, i will try this.
> I know for sure that my ISP is blocking the access to framagit.org.
> Can it also be because while installing arch using archinstall, i used my country 'India' for  the mirror?

I'd just refresh your mirrorlist and maybe add some extra countries. Because framagit isn't the only aur mirror. There are a lot and the reason ya got the error is because that specific mirror is down or cant be reached.
