### ISSUE TITLE
hyprV4 sound no workie; fairly newb, but did RTFM. :P

### ISSUE THREAD

**Issue by Paulie420** [SolDoesTech/HyprV4#41]
My volume/mic icons don't show up at hyprV4 boot. I don't have pulseaudio.service, nor pulseaudio package installed... I do have pipewire, but am a bit confused...

Do I need to install pulseaudio or can anyone help me diagnose the issue? I've modified v4 a lot, but nothing that should have broke this - it hasn't worked at all.

I'm on a framework laptop - arch linux, blah.
Thank you Sol!!! hyprV4 is so rad - its literally what sold me on TWMs; to be SHOWN how to modify the configs... I don't use a lot of the stock apps you setup w/ v4, but learned how to change things because of this theme. THANKS!

**Comment by milesje** [comment]
@Paulie420 I'm also using a framework laptop and installed V4 on a clean installed. I'm not having any issues with sound. Did you install after installing another DE/WM?

**Comment by Paulie420** [comment]
No - and its weird, b/c I just installed HyprV4 on a separate ThinkPad and it has the same sound issues! What it 'does' is theres no sound icons on the waybar - unless I click in the empty spaces were they should be... then they appear. If I hover over the speaker icon, it displays 'at 0%' - clicking it does nothing - right-clicking it drops a menu down, but the menu displays 'Establishing connection to PulseAudio. Please wait...'... forever. Same exact things happen on the microphone icon.

When I query pacman, no pulseaudio is installed - but pipewire is so I didn't know if I should install pulseaudio package - can you query yer system for anythin with 'pulse' and anything with 'wire'??? I *do* have 'pavucontrol' - another 'thing'... I can hear sound, but very low volume and the speaker function keys don't operate - can't turn up volume.

I just didn't wanna start throwing packages at it - was hoping someone @ hyprV4 would answer; maybe I'll ask on hyprland.
Loving the framework... cheers.

**Comment by Paulie420** [comment]
SOLVED -- So I just needed the 'pulseaudio' package. I was under the impression that 'pipewire' replaced pulse or something... derp. Maybe the hyprv4 install script should install puleaudio as I installed on a minimal Arch install. At any rate, I'm glad its fixed...
