### ISSUE TITLE
<Super> doesn't open menu

### ISSUE THREAD

**Issue by proJM-Coding** [SolDoesTech/HyprV4#42]
When I press my <super> key the start menu/launcher doesn't open it. I need to click on it to open instead. Is there some config I change to fix this?

**Comment by milesje** [comment]
Try <SUPER> + Space. This will open the wofi menu, it is a little different than the apps launcher, but does the same job. I'm sure the <SUPER> + Space can be changed to show the exact same as they are both using wofi.

**Comment by proJM-Coding** [comment]
Thanks for the help, I try looking at the config and see if it fixes it.

**Comment by proJM-Coding** [comment]
While I can't find a setting to change this it's nice that I can use SUPER + Space now. Thanks for the help

**Comment by milesje** [comment]
@proJM-Coding there is NOT a key binding to open the "menu/launcher". You can modify the Super + space (or create your own) which will open the same menu. If you want to know the exact wofi command that is being used the in waybar configuration look at ~/.config/HyprV/waybar/config/v4-config-bottom.jsonc 
In which case the command being run is below:
`sh -c '(sleep 0.5s; pkill wofi || wofi -c ~/.config/HyprV/wofi/config-lmenu)' & disown`
I don't think you map this command to just the Super key as the Super key is your mainMod. If you want you can change the mainMod to a different key such as the ALT key and then you should be able to map the Super by itself to launch the wofi command.
