### ISSUE TITLE
Stuck on lockscreen and can't access terminal

### ISSUE THREAD

**Issue by mathexresources** [SolDoesTech/HyprV4#57]
After updating monitor settings my screen went black, and after reboot im stuck on login screen, i login, insert right login credentials, and boom, black screen for few seconds and then back in lock screen, i probably do know how to fix it but i cant access terminal, i tried alt+shift+1 but cant access it, any way to access terminal or crash login screen?

**Comment by kurzwee** [comment]
soluce ? plz
