### ISSUE TITLE
Customizing buttons in waybar-bottom in V4

### ISSUE THREAD

**Issue by Anshu-Bijarnia** [SolDoesTech/HyprV4#8]
Can anyone please guide me how to edit the icons and the apps that launch using them in the bottom waybar in V4 layout? 
![image](https://github.com/SolDoesTech/HyprV4/assets/86189784/e4b5f3ec-2fd9-4aaa-bc5d-36bbb4ab2593)

**Comment by aleksandar-code** [comment]
Inside ~/.config/HyprV/waybar/conf/v4-config-bottom.jsonc

**Comment by ai-vaibhavv** [comment]
Hi, did you customise the button and it got stacked? how did you fix it?
