### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by Olkkulus** [SolDoesTech/HyprV4#86]
Just ran the install script on a fresh Arch install following a tutorial to be safe. After entering the correct username and password and pressing login, I get the message 'Login failed!'. Don't really know what else I can say..
I Have an AMD gpu, so shouldn't cause problems..?

**Comment by Olkkulus** [comment]
i guess just disable sddm and login thru terminal works..

**Comment by BigAdamO** [comment]
Do you remember how you solved this problem exactly? I have the same issue.

**Comment by Olkkulus** [comment]
This Hyprland install script just doesn't work. 

Do yourself a favor and either learn to install and configure it yourself, or do something else.
I learned to do it manually and don't regret it at all.
