### ISSUE TITLE
why need yay？

### ISSUE THREAD

**Issue by Brantfang** [SolDoesTech/HyprV4#92]
Can I use pacman instead of yay?

**Comment by fallenexistence0** [comment]
Yay is required as some of the packages in this script come from the AUR (Arch user repository), without yay (or a similiar package helper) you won't have access to the AUR. This link should help you if you are looking for yay alternatives: https://wiki.archlinux.org/title/AUR_helpers ,I personally just use yay, as it can be used to install from the official repositories like pacman, and gives me access to the aur.

Also here is a link in the arch wiki that may explain the aur better than me: https://wiki.archlinux.org/title/Arch_User_Repository

**Comment by Brantfang** [comment]
Thanks. Because of the use of packages from the AUR repository.
