### ISSUE TITLE
how do i remove the lower part of the waybar 

### ISSUE THREAD

**Issue by szymon420699** [SolDoesTech/HyprV4#94]
i tried chaning the config it didnt work it just removed the top and the botttom
please help me thanks

![2024-05-04-223459_hyprshot](https://github.com/SolDoesTech/HyprV4/assets/83908636/da775761-f6f2-4499-bff6-ad71d7b28362)

**Comment by szymon420699** [comment]
nevermind i found a solution 

remove or rename (which what i did) `v4-config-bottom.jsonc` to whatever you want. file path `~/.config/HyprV/waybar/conf`

**Comment by ai-vaibhavv** [comment]
Hi when you changed the wabar icons in the bottom, it got stacked, how did you fix it?
