### ISSUE TITLE
swww location

### ISSUE THREAD

**Issue by tomasolsinar** [SolDoesTech/HyprV4#96]
Hello, that's maybe a stupid issue but i am not able to find location of swww config files. I am talking about the script in which are set locations of backgrounds, transitions, etc. 
Thank you for answer.

**Comment by gitmanbloggus** [comment]
~/.config/ has all config files
including swww and hyprland

**Comment by tomasolsinar** [comment]
Yes but there is no swww dir. The thing I was looking for is in ~/.config/HyprV/hyprv_util
